# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator/v1/audio_input.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestrator/v1/audio_input.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from orchestrator.v1 import common_pb2 as orchestrator_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!orchestrator/v1/audio_input.proto\x12\x0forchestrator.v1\x1a\x1corchestrator/v1/common.proto\"=\n\rListenRequest\x12,\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1c.orchestrator.v1.AudioConfig\"@\n\x12\x43\x61pturedAudioChunk\x12*\n\x05\x63hunk\x18\x01 \x01(\x0b\x32\x1b.orchestrator.v1.AudioChunk2\xb8\x01\n\x11\x41udioInputService\x12R\n\tGetConfig\x12!.orchestrator.v1.GetConfigRequest\x1a\".orchestrator.v1.GetConfigResponse\x12O\n\x06Listen\x12\x1e.orchestrator.v1.ListenRequest\x1a#.orchestrator.v1.CapturedAudioChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator.v1.audio_input_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LISTENREQUEST']._serialized_start=84
  _globals['_LISTENREQUEST']._serialized_end=145
  _globals['_CAPTUREDAUDIOCHUNK']._serialized_start=147
  _globals['_CAPTUREDAUDIOCHUNK']._serialized_end=211
  _globals['_AUDIOINPUTSERVICE']._serialized_start=214
  _globals['_AUDIOINPUTSERVICE']._serialized_end=398
# @@protoc_insertion_point(module_scope)
