# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from orchestrator.v1 import audio_input_pb2 as orchestrator_dot_v1_dot_audio__input__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orchestrator/v1/audio_input_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioInputServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Listen = channel.unary_stream(
                '/orchestrator.v1.AudioInputService/Listen',
                request_serializer=orchestrator_dot_v1_dot_audio__input__pb2.ListenRequest.SerializeToString,
                response_deserializer=orchestrator_dot_v1_dot_audio__input__pb2.CapturedAudioChunk.FromString,
                _registered_method=True)


class AudioInputServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Listen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioInputServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Listen': grpc.unary_stream_rpc_method_handler(
                    servicer.Listen,
                    request_deserializer=orchestrator_dot_v1_dot_audio__input__pb2.ListenRequest.FromString,
                    response_serializer=orchestrator_dot_v1_dot_audio__input__pb2.CapturedAudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.v1.AudioInputService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.v1.AudioInputService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AudioInputService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Listen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/orchestrator.v1.AudioInputService/Listen',
            orchestrator_dot_v1_dot_audio__input__pb2.ListenRequest.SerializeToString,
            orchestrator_dot_v1_dot_audio__input__pb2.CapturedAudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
