# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'orchestrator/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1corchestrator/v1/common.proto\x12\x0forchestrator.v1\"<\n\x0bSpeakerInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0bmatching_id\x18\x03 \x01(\t\"4\n\x0b\x41udioConfig\x12\x13\n\x0bsample_rate\x18\x01 \x01(\r\x12\x10\n\x08\x63hannels\x18\x02 \x01(\r\"A\n\nAudioChunk\x12\x0f\n\x07samples\x18\x01 \x03(\x02\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEAKERINFO']._serialized_start=49
  _globals['_SPEAKERINFO']._serialized_end=109
  _globals['_AUDIOCONFIG']._serialized_start=111
  _globals['_AUDIOCONFIG']._serialized_end=163
  _globals['_AUDIOCHUNK']._serialized_start=165
  _globals['_AUDIOCHUNK']._serialized_end=230
# @@protoc_insertion_point(module_scope)
